### ISSUE TITLE
SimpleGranularity should be serialized as string

### ISSUE THREAD

**Issue by thomask** [pixelfederation/druid-php#4]
SimpleGranularity (#3781b61) does not get serialized to a string and as such is currently broken. This wasn't caught during testing since passing 'all' as the type (our main reason for adding the class) will work when sent in an object: 

``` json
{
    "granularity": {
        "granularity": "all",
        "type": "all",
    }
}
```

For other simple granularities to work, the desired output would actually be:

``` json
{
    "granularity": "all"
}
```

I am working on a PR where components can either implement the `TypedInterface` or a new `StringComponentInterface`. The plan is to conditionally serialize these components either as object or as string [using a handler](http://jmsyst.com/libs/serializer/master/handlers). There are [some issues](https://github.com/schmittjoh/serializer/issues/631) still to work out for this approach.

Any feedback would be appreciated.

**Comment by roloenusa** [comment]
Has there been any progress on merging the pull request? Not being able to use simple granularity does make it more difficult.
